"use client"
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header/Header"
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import Footer from "./components/Footer/Footer";
import React from "react";
import { Provider } from "react-redux";
import store from '../redux/store';
import Head from "next/head";
import { usePathname } from "next/navigation";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  
const pathname = usePathname(); 
const showHeader = !pathname.includes("/admin");

  return (
    <html lang="en">
     
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
            <Provider store={store}>
            <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
          </Head>
          {/* <Header /> */}
          {showHeader && <Header />}
        {children}
        <div className="mt-20"><Footer/></div>
        </Provider>
      </body>
    </html>
  );
}
